on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: runs typescript and jest

    steps:
      - name: Install Dependencies for Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install build-essential libssl-dev libkrb5-dev libc++-dev
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm test
